### ISSUE TITLE
File name conflicts on case-insensitive filesystems

### ISSUE THREAD

**Issue by cfxegbert** [eza-community/powertest#10]
The default filesystem on MacOS is case-insensitive but has case preserving file names. If the test generation has arguments that just differ in case a case-insensitive file name conflict may happen.   This happens on eza with
* ptest_tests_test_dir_-l_--sort_Ext.toml => ptest_tests_test_dir_-l_--sort_ext.toml
* ptest_tests_test_dir_-l_--sort_Name.toml => ptest_tests_test_dir_-l_--sort_name.toml
* ptest_tests_test_dir_-l_--sort_Extension.toml => ptest_tests_test_dir_-l_--sort_extension.toml
* ptest_tests_test_dir_-l_--sort_Filename.toml => ptest_tests_test_dir_-l_--sort_filename.toml
* ptest_tests_test_dir_-l_-s_Ext.toml => ptest_tests_test_dir_-l_-s_ext.toml
* ptest_tests_test_dir_-l_-s_Extension.toml => ptest_tests_test_dir_-l_-s_extension.toml
* ptest_tests_test_dir_-l_-s_Filename.toml => ptest_tests_test_dir_-l_-s_filename.toml
* ptest_tests_test_dir_-l_-s_Name.toml => ptest_tests_test_dir_-l_-s_name.toml

**Comment by cafkafk** [comment]
Should be solved by #9
